#!/usr/bin/env bash
#
# update-from-template.sh — pull template improvements in, and open the pull
# request for them.
#
#     scripts/update-from-template.sh
#
# Plain shell on purpose: this is the one maintenance task every project needs
# regardless of which agent, editor or none you happen to be using, so it does
# not live under .claude/ and does not depend on anything vendor-specific.
#
# WHAT IT DOES, in one run: updates from the template, works out which version
# you landed on, branches as template/<version>, commits, pushes, and opens the
# pull request. From there the pipeline takes over — CI, and the `template-sync`
# check that proves this branch is exactly the template's output and nothing
# else, which is what lets it skip the `plan` check.
#
# WHAT IT WILL NOT DO: resolve a conflict. If the template changed a file you
# also changed here, copier leaves both versions in the file and this stops, so
# you decide rather than a script guessing.
#
# Options:
#   --ref <ref>    update to a specific template ref instead of its latest tag.
#                  Use this to test a template change that has merged but is not
#                  tagged yet: --ref HEAD
#   --base <b>     update a run's base branch instead of the default branch
#                  (the same flag deliver-loop.sh and setup-github.sh take).
#                  The checkout must BE on that branch; the update branches off
#                  it, carries its lane suffix, and the pull request targets it.
#                  Without this, every step assumed the default branch and a
#                  lane could be driven but never updated (anvil mobo F1).
#   --no-pr        do everything except open the pull request.

set -euo pipefail

REF=""
OPEN_PR=1
BASE_FLAG=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --ref)    REF="${2:-}"; shift 2 ;;
    --base)   [[ -n "${2:-}" ]] || { echo "update-from-template: --base needs a branch name" >&2; exit 2; }
              BASE_FLAG="$2"; shift 2 ;;
    --no-pr)  OPEN_PR=0; shift ;;
    -h|--help)
      sed -n '2,26p' "$0" | sed -n 's/^# \{0,1\}//p'
      exit 0 ;;
    *) echo "update-from-template: unknown argument: $1" >&2; exit 2 ;;
  esac
done

die() { echo "update-from-template: $*" >&2; exit 1; }

ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || die "not inside a git repository"
cd "$ROOT"

command -v copier >/dev/null 2>&1 \
  || die "copier is not installed. Install it once per machine:

    uv tool install copier"

ANSWERS=".copier-answers.yml"
[[ -f "$ANSWERS" ]] || die "no $ANSWERS here.

This project was not generated by Copier, or the answers file was deleted.
Without it there is no record of which template this came from."

# copier refuses to update a dirty tree, and it is right to: it needs to tell
# its own changes apart from yours. Failing here with a clear reason beats
# failing inside copier with a less obvious one.
[[ -z "$(git status --porcelain)" ]] || die "you have uncommitted changes.

Commit or stash them first — the update has to be the only thing in this
branch, or the template-sync check will (correctly) reject the pull request."

# Work out the default branch, tolerating every way it can be unknown.
#
# `|| true` is load-bearing. refs/remotes/origin/HEAD is written by `git clone`
# but NOT by `git remote add`, which is how a project created with
# `gh repo create --source=.` gets its remote — so this lookup failing is the
# normal case, not an edge one. Under `set -e` with `pipefail`, a failed command
# substitution ends the script, and `--quiet` means it would do so without
# printing anything at all.
DEFAULT_BRANCH="$(git symbolic-ref --quiet --short refs/remotes/origin/HEAD 2>/dev/null \
  | sed 's|^origin/||' || true)"
if [[ -z "$DEFAULT_BRANCH" ]]; then
  for candidate in main master; do
    if git show-ref --verify --quiet "refs/heads/$candidate"; then
      DEFAULT_BRANCH="$candidate"
      break
    fi
  done
fi
DEFAULT_BRANCH="${DEFAULT_BRANCH:-main}"
# The update's base: the default branch, or the run base named with --base —
# the same per-base lane isolation the driver and the setup script already
# have. A lane branch gets the driver's own suffix on the update branch so
# twin runs updating to the same version cannot collide on its name.
BASE="${BASE_FLAG:-$DEFAULT_BRANCH}"
LANE=""
if [[ "$BASE" != "$DEFAULT_BRANCH" ]]; then
  LANE="--$(printf '%s' "$BASE" | tr -c 'A-Za-z0-9._-' '-')"
fi
CURRENT="$(git rev-parse --abbrev-ref HEAD)"
[[ "$CURRENT" == "$BASE" ]] || die "you are on '$CURRENT', not '$BASE'.

A template update branches off its base branch, so that the pull request
contains the update and nothing else. Updating a run's base branch instead of
the default one? Name it: --base <branch>."

# Refresh from the remote if there is one. A failure here is worth a warning
# rather than a stop: it means the base may be a little old, which makes the
# pull request slightly stale but never wrong — template-sync compares against
# whatever base the pull request actually has.
if git remote get-url origin >/dev/null 2>&1; then
  echo "update-from-template: refreshing $BASE"
  git pull --ff-only origin "$BASE" \
    || echo "update-from-template: could not refresh from origin; continuing on the local $BASE" >&2
else
  echo "update-from-template: no 'origin' remote; working from the local $BASE"
fi

BEFORE="$(awk '/^_commit:/ { print $2; exit }' "$ANSWERS" | tr -d '"'"'"'')"
echo "update-from-template: currently on template ${BEFORE:-<unknown>}"

echo "update-from-template: running copier update"
echo "update-from-template: (copier may print 'Make sure Git >= 2.24 is installed' — that is copier's stock advisory, not a real prerequisite failure; any modern git satisfies it)"
if [[ -n "$REF" ]]; then
  copier update --defaults --trust --vcs-ref="$REF"
else
  copier update --defaults --trust
fi

AFTER="$(awk '/^_commit:/ { print $2; exit }' "$ANSWERS" | tr -d '"'"'"'')"

if [[ -z "$(git status --porcelain)" ]]; then
  echo "update-from-template: already up to date with the template ($AFTER). Nothing to do."
  exit 0
fi

# Copier resolves what it can and leaves the rest marked, the same way git does
# for a merge. Those markers must never reach a commit: they are not valid code,
# and a script cannot know which side you meant.
if git grep -lI --no-index -e '^<<<<<<< ' -e '^>>>>>>> ' -- . ':(exclude).git' 2>/dev/null | grep -q .; then
  echo >&2
  echo "update-from-template: the update produced CONFLICTS." >&2
  echo >&2
  echo "The template changed files this project has also changed, so copier left" >&2
  echo "both versions in place with markers around them:" >&2
  echo >&2
  git grep -lI --no-index -e '^<<<<<<< ' -- . ':(exclude).git' 2>/dev/null | sed 's/^/    /' >&2
  cat >&2 <<'EOF'

Open each one, keep the version you want, and delete the markers. Then finish
by hand:

    git switch -c template/<version>
    git commit -am "Update from template <version>"
    git push -u origin HEAD

Nothing has been committed, so `git checkout -- .` backs the whole update out
if you would rather deal with it later.
EOF
  exit 1
fi

BRANCH="template/${AFTER}${LANE}"
if git show-ref --verify --quiet "refs/heads/$BRANCH"; then
  die "branch '$BRANCH' already exists.

An update to $AFTER has been started before. Finish or delete that branch:

    git branch -D $BRANCH"
fi

echo "update-from-template: ${BEFORE:-<unknown>} -> ${AFTER}"
git switch -c "$BRANCH"
git add -A
git commit -m "Update from template ${AFTER}"

if ! git remote get-url origin >/dev/null 2>&1; then
  echo "update-from-template: committed on $BRANCH. No 'origin' remote, so"
  echo "update-from-template: nothing was pushed and no pull request was opened."
  exit 0
fi

# WHO OPENS THE PULL REQUEST (ESC-63), decided BEFORE the push because one of
# the answers must ride in it. Never the ambient login: an update touches
# CODEOWNERS-owned gate paths, so its pull request NEEDS the owner's review —
# and GitHub refuses an author's approval of their own pull request, so an
# owner-authored update was unapprovable by construction (this script's old
# ending demanded both at once). The App authors it instead, one of two ways —
# the driver's credential rule, in script form:
#   1. the App mints here -> open directly with the minted token;
#   2. minting is impossible but gh still answers (a hosted session whose
#      platform owns the credential) -> commit .pr-request.json as this
#      branch's last commit; the push fires open-pr.yml server-side and the
#      pull request arrives App-authored;
#   3. neither -> push, and say exactly what remains.
PR_VIA="none"
APP_TOKEN=""
if [[ "$OPEN_PR" -eq 1 ]] && command -v gh >/dev/null 2>&1; then
  if [[ -x .claude/scripts/app-token.sh ]]; then
    APP_TOKEN="$(.claude/scripts/app-token.sh 2>/dev/null || true)"
  fi
  if [[ -n "$APP_TOKEN" ]]; then
    PR_VIA="direct"
  elif gh api user >/dev/null 2>&1 && [[ -f .github/workflows/open-pr.yml ]]; then
    PR_VIA="marker"
    printf '{"base": "%s", "title": "Update from template %s", "body": "Mechanical update from the project template, %s to %s, produced by scripts/update-from-template.sh. The template-sync check verifies this branch is byte-for-byte copier update output, which is what lets it skip the plan check. Expect to approve it: it touches CODEOWNERS-owned gate paths."}\n' \
      "$BASE" "$AFTER" "${BEFORE:-unknown}" "$AFTER" > .pr-request.json
    git add .pr-request.json
    git commit -m "Request the pull request"
  fi
fi

git push -u origin "$BRANCH"

case "$PR_VIA" in
  direct)
    GH_TOKEN="$APP_TOKEN" gh pr create \
      --base "$BASE" \
      --head "$BRANCH" \
      --title "Update from template ${AFTER}" \
      --body "Mechanical update from the project template, ${BEFORE:-<unknown>} to ${AFTER}.

Produced by \`scripts/update-from-template.sh\`. The \`template-sync\` check
verifies that this branch is byte-for-byte \`copier update\` output and carries
nothing hand-written, which is what allows it to skip the \`plan\` check." ;;
  marker)
    echo "update-from-template: pushed $BRANCH with a .pr-request.json aboard —"
    echo "update-from-template: the push fires open-pr.yml and the pull request"
    echo "update-from-template: arrives authored by the App within a minute or two." ;;
  none)
    if [[ "$OPEN_PR" -eq 0 ]]; then
      echo "update-from-template: pushed $BRANCH. Open the pull request when ready."
    elif ! command -v gh >/dev/null 2>&1; then
      echo "update-from-template: pushed $BRANCH, but the GitHub CLI is not installed,"
      echo "update-from-template: so open the pull request yourself. Install it with:"
      echo "    brew install gh      # macOS"
      echo "    sudo pacman -S github-cli   # Arch"
    else
      echo "update-from-template: pushed $BRANCH, but no credential here can author"
      echo "update-from-template: the pull request AS THE APP (the mint failed and no"
      echo "update-from-template: server-side opener is available). Open it yourself —"
      echo "update-from-template: and note an author cannot approve their own pull"
      echo "update-from-template: request, so an owner-authored one needs another"
      echo "update-from-template: reviewer for its CODEOWNERS paths."
    fi
    exit 0 ;;
esac

cat <<EOF

update-from-template: done.

The pipeline takes it from here. Two things to expect:

  - template-sync must go green. If it fails, this branch has something in it
    that copier did not produce.
  - You will have to approve it. A template update touches CODEOWNERS-owned
    paths, and the App authored the pull request precisely so that your
    approval counts — GitHub refuses an author's approval of their own pull
    request, which is why this script no longer opens it as you.
EOF
